[2024-01-04T18:22:46.454+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:22:46.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:22:46.455+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:22:46.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:22:46.460+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:22:46.459+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:22:46.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:22:46.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.026 seconds
[2024-01-04T18:23:16.603+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:23:16.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:23:16.606+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:23:16.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:23:16.620+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:23:16.617+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:23:16.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:23:16.637+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.041 seconds
[2024-01-04T18:23:46.872+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:23:46.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:23:46.875+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:23:46.874+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:23:46.882+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:23:46.881+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:23:46.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:23:46.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.034 seconds
[2024-01-04T18:24:17.155+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:24:17.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:24:17.158+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:24:17.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:24:17.165+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:24:17.163+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:24:17.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:24:17.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.031 seconds
[2024-01-04T18:25:20.409+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:25:20.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:25:20.410+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:25:20.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:25:20.413+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:25:20.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:25:20.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:25:20.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.015 seconds
[2024-01-04T18:25:50.652+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:25:50.653+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:25:50.654+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:25:50.653+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:25:50.659+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:25:50.658+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:25:50.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:25:50.688+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.040 seconds
[2024-01-04T18:27:19.766+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:27:19.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:27:19.768+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:27:19.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:27:19.772+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:27:19.771+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:27:19.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:27:19.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.020 seconds
[2024-01-04T18:28:02.726+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:28:02.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:28:02.729+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:28:02.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:28:02.735+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:28:02.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:28:02.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:28:02.755+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.032 seconds
[2024-01-04T18:28:32.859+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:28:32.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:28:32.861+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:28:32.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:28:32.866+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:28:32.865+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:28:32.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:28:32.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.028 seconds
[2024-01-04T18:29:03.257+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:29:03.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:29:03.260+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:29:03.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:29:03.266+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:29:03.265+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:29:03.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:29:03.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.028 seconds
[2024-01-04T18:29:33.640+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:29:33.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:29:33.643+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:29:33.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:29:33.647+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:29:33.647+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:29:33.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:29:33.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.026 seconds
[2024-01-04T18:30:04.116+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:30:04.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:30:04.120+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:30:04.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:30:04.127+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:30:04.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:30:04.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:30:04.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.035 seconds
[2024-01-04T18:30:34.262+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:30:34.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:30:34.265+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:30:34.264+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:30:34.271+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:30:34.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:30:34.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:30:34.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.031 seconds
[2024-01-04T18:31:04.414+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:31:04.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:31:04.417+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:31:04.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:31:04.425+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:31:04.423+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:31:04.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:31:04.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.033 seconds
[2024-01-04T18:35:54.382+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:35:54.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:35:54.387+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:35:54.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:35:54.402+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:35:54.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:35:54.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:35:54.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.055 seconds
[2024-01-04T18:36:24.708+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:36:24.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:36:24.737+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:36:24.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:36:24.761+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:36:24.750+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:36:24.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:36:24.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.192 seconds
[2024-01-04T18:36:55.148+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:36:55.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:36:55.154+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:36:55.152+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:36:55.169+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:36:55.166+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:36:55.169+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:36:55.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.068 seconds
[2024-01-04T18:37:25.354+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:37:25.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:37:25.357+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:37:25.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:37:25.366+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:37:25.363+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:37:25.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:37:25.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.088 seconds
[2024-01-04T18:37:55.572+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:37:55.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:37:55.581+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:37:55.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:37:55.600+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:37:55.597+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:37:55.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:37:55.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.135 seconds
[2024-01-04T18:38:25.866+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:38:25.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:38:25.868+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:38:25.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:38:25.873+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:38:25.872+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:38:25.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:38:25.890+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.028 seconds
[2024-01-04T18:38:56.066+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:38:56.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:38:56.068+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:38:56.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:38:56.073+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:38:56.072+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:38:56.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:38:56.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.031 seconds
[2024-01-04T18:39:26.270+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:39:26.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:39:26.273+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:39:26.272+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:39:26.279+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:39:26.277+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:39:26.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:39:26.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.035 seconds
[2024-01-04T18:49:18.110+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:49:18.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:49:18.111+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:49:18.111+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:49:18.114+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:49:18.113+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:49:18.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:49:18.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.016 seconds
[2024-01-04T18:49:48.305+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:49:48.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:49:48.307+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:49:48.306+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:49:48.313+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:49:48.311+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:49:48.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:49:48.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.028 seconds
[2024-01-04T18:50:18.767+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:50:18.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:50:18.771+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:50:18.770+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:50:18.779+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:50:18.777+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:50:18.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:50:18.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.039 seconds
[2024-01-04T18:50:49.242+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:50:49.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:50:49.246+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:50:49.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:50:49.253+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:50:49.252+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:50:49.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:50:49.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.050 seconds
[2024-01-04T18:51:19.618+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:51:19.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:51:19.620+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:51:19.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:51:19.625+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:51:19.624+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:51:19.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:51:19.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.025 seconds
[2024-01-04T18:51:49.881+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:51:49.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:51:49.887+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:51:49.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:51:49.896+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:51:49.894+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:51:49.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:51:49.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.043 seconds
[2024-01-04T18:52:20.010+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:52:20.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:52:20.014+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:52:20.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:52:20.021+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:52:20.020+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:52:20.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:52:20.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.035 seconds
[2024-01-04T18:52:50.152+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:52:50.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:52:50.155+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:52:50.155+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:52:50.162+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:52:50.161+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:52:50.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:52:50.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.034 seconds
[2024-01-04T18:53:20.297+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:53:20.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:53:20.301+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:53:20.300+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:53:20.308+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:53:20.307+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:53:20.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:53:20.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T18:53:51.316+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:53:51.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:53:51.319+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:53:51.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:53:51.352+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:53:51.349+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:53:51.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:53:51.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.067 seconds
[2024-01-04T18:54:21.607+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:54:21.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:54:21.611+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:54:21.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:54:21.617+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:54:21.616+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:54:21.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:54:21.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.031 seconds
[2024-01-04T18:54:52.108+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:54:52.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:54:52.112+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:54:52.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:54:52.120+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:54:52.119+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:54:52.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:54:52.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.042 seconds
[2024-01-04T18:55:22.454+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:55:22.455+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:55:22.456+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:55:22.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:55:22.463+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:55:22.461+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:55:22.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:55:22.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.030 seconds
[2024-01-04T18:55:52.906+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:55:52.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:55:52.909+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:55:52.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:55:52.915+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:55:52.914+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:55:52.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:55:52.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.034 seconds
[2024-01-04T18:56:23.090+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:56:23.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:56:23.093+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:56:23.092+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:56:23.101+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:56:23.099+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:56:23.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:56:23.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.038 seconds
[2024-01-04T18:56:53.242+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:56:53.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:56:53.245+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:56:53.244+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:56:53.252+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:56:53.251+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:56:53.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:56:53.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.034 seconds
[2024-01-04T18:57:23.383+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:57:23.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:57:23.387+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:57:23.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:57:23.395+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:57:23.393+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:57:23.396+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:57:23.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.034 seconds
[2024-01-04T18:57:54.378+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:57:54.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:57:54.381+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:57:54.381+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:57:54.389+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:57:54.388+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:57:54.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:57:54.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T18:58:24.721+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:58:24.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:58:24.724+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:58:24.724+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:58:24.732+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:58:24.731+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:58:24.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:58:24.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.035 seconds
[2024-01-04T18:58:54.880+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:58:54.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:58:54.884+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:58:54.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:58:54.892+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:58:54.891+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:58:54.893+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:58:54.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.038 seconds
[2024-01-04T18:59:25.475+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:59:25.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:59:25.480+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:59:25.479+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:59:25.488+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:59:25.486+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:59:25.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:59:25.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.047 seconds
[2024-01-04T18:59:55.944+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:59:55.946+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T18:59:55.951+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:59:55.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:59:55.957+0000] {logging_mixin.py:188} INFO - [2024-01-04T18:59:55.956+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T18:59:55.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T18:59:55.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T19:00:26.360+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:00:26.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:00:26.364+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:00:26.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:00:26.371+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:00:26.370+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:00:26.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:00:26.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.036 seconds
[2024-01-04T19:00:56.817+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:00:56.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:00:56.820+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:00:56.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:00:56.827+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:00:56.826+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:00:56.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:00:56.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T19:01:27.265+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:01:27.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:01:27.268+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:01:27.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:01:27.273+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:01:27.272+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:01:27.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:01:27.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.031 seconds
[2024-01-04T19:01:57.676+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:01:57.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:01:57.680+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:01:57.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:01:57.687+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:01:57.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:01:57.687+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:01:57.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.036 seconds
[2024-01-04T19:02:28.105+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:02:28.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:02:28.108+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:02:28.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:02:28.114+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:02:28.113+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:02:28.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:02:28.133+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.033 seconds
[2024-01-04T19:02:58.545+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:02:58.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:02:58.547+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:02:58.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:02:58.558+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:02:58.557+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:02:58.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:02:58.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.042 seconds
[2024-01-04T19:03:01.769+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:03:01.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:03:01.771+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:03:01.771+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:03:01.780+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:03:01.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:03:01.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:03:01.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.032 seconds
[2024-01-04T19:03:32.032+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:03:32.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:03:32.035+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:03:32.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:03:32.043+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:03:32.041+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:03:32.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:03:32.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T19:04:02.296+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:02.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:04:02.305+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:04:02.303+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:02.319+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:04:02.316+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:04:02.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:02.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.071 seconds
[2024-01-04T19:04:13.275+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:13.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:04:13.277+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:04:13.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:13.281+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:04:13.280+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:04:13.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:13.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.023 seconds
[2024-01-04T19:04:43.450+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:43.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:04:43.454+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:04:43.453+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:43.462+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:04:43.460+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:04:43.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:04:43.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.079 seconds
[2024-01-04T19:05:13.722+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:05:13.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:05:13.726+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:05:13.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:05:13.734+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:05:13.732+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:05:13.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:05:13.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T19:05:43.977+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:05:43.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:05:43.981+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:05:43.980+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:05:43.989+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:05:43.987+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:05:43.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:05:44.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T19:06:14.242+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:06:14.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:06:14.246+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:06:14.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:06:14.254+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:06:14.252+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:06:14.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:06:14.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.033 seconds
[2024-01-04T19:06:44.520+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:06:44.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:06:44.523+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:06:44.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:06:44.531+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:06:44.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:06:44.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:06:44.561+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.047 seconds
[2024-01-04T19:07:28.265+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:07:28.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:07:28.266+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:28.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:07:28.286+0000] {processor.py:840} INFO - DAG(s) 'simple_pipeline' retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:07:28.389+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:28.389+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:simple_pipeline
[2024-01-04T19:07:28.394+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:28.394+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:simple_pipeline
[2024-01-04T19:07:28.399+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:28.398+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:simple_pipeline
[2024-01-04T19:07:28.399+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:28.399+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-04T19:07:28.404+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:28.404+0000] {dag.py:3055} INFO - Creating ORM DAG for simple_pipeline
[2024-01-04T19:07:28.409+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:28.409+0000] {dag.py:3820} INFO - Setting next_dagrun for simple_pipeline to 2024-01-03T00:00:00+00:00, run_after=2024-01-04T00:00:00+00:00
[2024-01-04T19:07:28.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.156 seconds
[2024-01-04T19:07:59.541+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:07:59.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:07:59.543+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:59.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:07:59.568+0000] {processor.py:840} INFO - DAG(s) 'simple_pipeline' retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:07:59.592+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:59.592+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-04T19:07:59.604+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:07:59.604+0000] {dag.py:3820} INFO - Setting next_dagrun for simple_pipeline to 2024-01-03T00:00:00+00:00, run_after=2024-01-04T00:00:00+00:00
[2024-01-04T19:07:59.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.087 seconds
[2024-01-04T19:08:17.856+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:08:17.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:08:17.859+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:08:17.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:08:17.872+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:08:17.869+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:08:17.873+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:08:17.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.041 seconds
[2024-01-04T19:18:51.810+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:18:51.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:18:51.811+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:18:51.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:18:51.854+0000] {processor.py:840} INFO - DAG(s) 'mysql_to_postgres_migration' retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:18:51.947+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:18:51.947+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:mysql_to_postgres_migration
[2024-01-04T19:18:51.952+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:18:51.951+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:mysql_to_postgres_migration
[2024-01-04T19:18:51.956+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:18:51.956+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:mysql_to_postgres_migration
[2024-01-04T19:18:51.956+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:18:51.956+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-04T19:18:51.961+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:18:51.961+0000] {dag.py:3055} INFO - Creating ORM DAG for mysql_to_postgres_migration
[2024-01-04T19:18:51.965+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:18:51.965+0000] {dag.py:3820} INFO - Setting next_dagrun for mysql_to_postgres_migration to 2024-01-01T00:00:00+00:00, run_after=2024-01-01T00:05:00+00:00
[2024-01-04T19:18:51.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.164 seconds
[2024-01-04T19:19:23.058+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:19:23.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:19:23.061+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:19:23.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:19:23.091+0000] {processor.py:840} INFO - DAG(s) 'mysql_to_postgres_migration' retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:19:23.108+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:19:23.107+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-04T19:19:23.121+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:19:23.121+0000] {dag.py:3820} INFO - Setting next_dagrun for mysql_to_postgres_migration to 2024-01-01T00:00:00+00:00, run_after=2024-01-01T00:05:00+00:00
[2024-01-04T19:19:23.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.079 seconds
[2024-01-04T19:19:53.413+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:19:53.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:19:53.417+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:19:53.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:19:53.447+0000] {processor.py:840} INFO - DAG(s) 'mysql_to_postgres_migration' retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:19:53.463+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:19:53.463+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2024-01-04T19:19:53.484+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:19:53.484+0000] {dag.py:3820} INFO - Setting next_dagrun for mysql_to_postgres_migration to 2024-01-01T00:00:00+00:00, run_after=2024-01-01T00:05:00+00:00
[2024-01-04T19:19:53.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.088 seconds
[2024-01-04T19:24:22.424+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:24:22.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:24:22.426+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:24:22.425+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:24:22.431+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:24:22.430+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:24:22.431+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:24:22.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.025 seconds
[2024-01-04T19:24:52.727+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:24:52.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:24:52.730+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:24:52.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:24:52.739+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:24:52.737+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:24:52.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:24:52.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.036 seconds
[2024-01-04T19:25:23.116+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:25:23.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:25:23.120+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:25:23.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:25:23.127+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:25:23.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:25:23.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:25:23.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.033 seconds
[2024-01-04T19:25:53.587+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:25:53.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:25:53.590+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:25:53.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:25:53.597+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:25:53.596+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:25:53.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:25:53.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.037 seconds
[2024-01-04T19:26:23.915+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:26:23.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:26:23.918+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:26:23.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:26:23.926+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:26:23.925+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:26:23.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:26:23.944+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.035 seconds
[2024-01-04T19:26:54.064+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:26:54.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:26:54.069+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:26:54.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:26:54.077+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:26:54.076+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:26:54.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:26:54.095+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.035 seconds
[2024-01-04T19:27:24.246+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:27:24.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:27:24.249+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:27:24.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:27:24.256+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:27:24.255+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:27:24.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:27:24.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.028 seconds
[2024-01-04T19:27:38.410+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:27:38.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:27:38.412+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:27:38.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:27:38.414+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:27:38.414+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:27:38.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:27:38.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.015 seconds
[2024-01-04T19:28:08.550+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:28:08.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:28:08.552+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:28:08.552+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:28:08.558+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:28:08.556+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:28:08.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:28:08.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.027 seconds
[2024-01-04T19:28:38.846+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:28:38.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:28:38.849+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:28:38.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:28:38.856+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:28:38.855+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:28:38.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:28:38.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.034 seconds
[2024-01-04T19:29:09.134+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:29:09.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:29:09.137+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:29:09.137+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:29:09.144+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:29:09.143+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:29:09.145+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:29:09.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.031 seconds
[2024-01-04T19:29:39.407+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:29:39.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:29:39.410+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:29:39.409+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:29:39.416+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:29:39.415+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:29:39.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:29:39.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.028 seconds
[2024-01-04T19:30:09.696+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:30:09.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:30:09.699+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:30:09.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:30:09.704+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:30:09.703+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:30:09.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:30:09.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.027 seconds
[2024-01-04T19:31:12.447+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:31:12.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:31:12.453+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:31:12.451+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:31:12.466+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:31:12.462+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:31:12.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:31:12.491+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.051 seconds
[2024-01-04T19:31:43.104+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:31:43.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:31:43.158+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:31:43.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:31:43.293+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:31:43.276+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:31:43.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:31:43.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.462 seconds
[2024-01-04T19:32:13.800+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:32:13.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:32:13.818+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:32:13.811+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:32:13.857+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:32:13.849+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:32:13.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:32:13.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.175 seconds
[2024-01-04T19:32:44.318+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:32:44.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:32:44.323+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:32:44.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:32:44.333+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:32:44.332+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:32:44.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:32:44.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.046 seconds
[2024-01-04T19:33:14.769+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:33:14.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:33:14.772+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:33:14.771+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:33:14.778+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:33:14.777+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:33:14.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:33:14.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.035 seconds
[2024-01-04T19:33:45.148+0000] {processor.py:161} INFO - Started process (PID=74) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:33:45.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:33:45.151+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:33:45.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:33:45.158+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:33:45.157+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:33:45.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:33:45.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.039 seconds
[2024-01-04T19:34:13.973+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:34:13.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:34:13.976+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:34:13.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:34:13.982+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:34:13.981+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:34:13.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:34:13.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.029 seconds
[2024-01-04T19:34:44.115+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:34:44.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/mysql_to_postgres.py for tasks to queue
[2024-01-04T19:34:44.118+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:34:44.117+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:34:44.124+0000] {logging_mixin.py:188} INFO - [2024-01-04T19:34:44.123+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/mysql_to_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/mysql_to_postgres.py", line 3, in <module>
    from airflow.providers.mysql.operators.mysql_to_postgres import MySqlToPostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.mysql.operators.mysql_to_postgres'
[2024-01-04T19:34:44.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/mysql_to_postgres.py
[2024-01-04T19:34:44.141+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/mysql_to_postgres.py took 0.030 seconds
